#!/usr/bin/env bash

DATASET=$1
MR=$2
NUM_NEG=$3
HOP=$4
LR=$5
L2=$6
EXP_NAME=$7
EPOCH=$8
GPU=$9
INIT_ADD_IDENTIFIERS=${10}
CUT_ENABLE=${11}
VERSION=${12}
GSN_TYPE=${13}
ONE_HOT_ENABLE=${14}
ID_TYPE=${15}
K=${16}
ACTIVATE_FUNC_TYPE=${17}
EDGE_IDENTIFIER_ACTIVATE_FUNC_TYPE=${18}
MIN_NODE=${19}
MAX_NODE=${20}
MIN_EDGE=${21}
MAX_EDGE=${22}
GNN_AGG_TYPE=${23}

for idx in "0" "1" "2" "3" "4"
do
    bash run_once.sh $DATASET $MR $NUM_NEG $HOP $LR $L2 "$EXP_NAME"_$idx $EPOCH $GPU $INIT_ADD_IDENTIFIERS $CUT_ENABLE $VERSION $GSN_TYPE $ONE_HOT_ENABLE \
    $ID_TYPE $K $ACTIVATE_FUNC_TYPE $EDGE_IDENTIFIER_ACTIVATE_FUNC_TYPE $MIN_NODE $MAX_NODE $MIN_EDGE $MAX_EDGE $GNN_AGG_TYPE
done
